use chrono::{DateTime, Utc};
use pgvector::Vector;
use serde::{Deserialize, Serialize};
use sqlx::prelude::FromRow;
use sqlx::types::Json;
use uuid::Uuid;

/// Complete representation of a row from the 'datasets' table.
///
/// This structure represents a persisted dataset with all database fields,
/// including system-generated identifiers and timestamps. It maps directly
/// to the PostgreSQL schema and is used for reading data from the database.
///
/// # Fields
///
/// * `id` - Unique identifier (UUID) generated by the database
/// * `original_id` - Original identifier from the source portal
/// * `source_portal` - Base URL of the originating CKAN portal
/// * `url` - Public landing page URL for the dataset
/// * `title` - Human-readable dataset title
/// * `description` - Optional detailed description
/// * `embedding` - Optional 1536-dimensional vector for semantic search
/// * `metadata` - Additional metadata stored as JSONB
/// * `first_seen_at` - Timestamp when the dataset was first indexed
/// * `last_updated_at` - Timestamp of the most recent update
#[derive(Debug, FromRow, Serialize, Clone)]
pub struct Dataset {
    /// Unique identifier (UUID) generated by the database
    pub id: Uuid,
    /// Original identifier from the source portal
    pub original_id: String,
    /// Base URL of the originating CKAN portal
    pub source_portal: String,
    /// Public landing page URL for the dataset
    pub url: String,
    /// Human-readable dataset title
    pub title: String,
    /// Optional detailed description
    pub description: Option<String>,

    /// Optional 1536-dimensional vector for semantic search (pgvector type)
    pub embedding: Option<Vector>,

    /// Additional metadata stored as JSONB
    pub metadata: Json<serde_json::Value>,

    /// Timestamp when the dataset was first indexed
    pub first_seen_at: DateTime<Utc>,
    /// Timestamp of the most recent update
    pub last_updated_at: DateTime<Utc>,
}

/// Data Transfer Object for inserting or updating datasets.
///
/// This structure is used when creating new datasets or updating existing ones.
/// Unlike `Dataset`, it doesn't include database-generated fields like `id` or
/// timestamps. The embedding field uses pgvector's `Vector` for database storage.
///
/// # Fields
///
/// * `original_id` - Original identifier from the source portal
/// * `source_portal` - Base URL of the originating CKAN portal
/// * `url` - Public landing page URL for the dataset
/// * `title` - Human-readable dataset title
/// * `description` - Optional detailed description
/// * `embedding` - Optional vector of 1536 floats (pgvector)
/// * `metadata` - Additional metadata as JSON
#[derive(Debug, Serialize, Clone)]
pub struct NewDataset {
    /// Original identifier from the source portal
    pub original_id: String,
    /// Base URL of the originating CKAN portal
    pub source_portal: String,
    /// Public landing page URL for the dataset
    pub url: String,
    /// Human-readable dataset title
    pub title: String,
    /// Optional detailed description
    pub description: Option<String>,
    /// Optional vector of 1536 floats (converted to pgvector on storage)
    pub embedding: Option<Vector>,
    /// Additional metadata as JSON
    pub metadata: serde_json::Value,
}

/// Risultato di una ricerca semantica con score di similarità
///
/// Questa struttura combina un dataset con il suo score di similarità rispetto
/// alla query di ricerca. Lo score rappresenta la cosine similarity tra l'embedding
/// del dataset e l'embedding della query, con valori tra 0.0 (nessuna similarità)
/// e 1.0 (identici).
#[derive(Debug, Serialize, Clone)]
pub struct SearchResult {
    /// Il dataset trovato
    pub dataset: Dataset,
    /// Score di similarità (0.0-1.0), dove 1.0 è match perfetto
    pub similarity_score: f32,
}

/// Statistiche del database per la dashboard
///
/// Fornisce una panoramica dello stato del database, utile per dashboard
/// e monitoring.
#[derive(Debug, Serialize, Clone)]
pub struct DatabaseStats {
    /// Numero totale di dataset nel database
    pub total_datasets: i64,
    /// Numero di dataset con embeddings generati
    pub datasets_with_embeddings: i64,
    /// Numero di portali unici indicizzati
    pub total_portals: i64,
    /// Timestamp dell'ultimo update
    pub last_update: Option<DateTime<Utc>>,
}

/// Portale configurato in portals.toml
///
/// Rappresenta un portale open data configurato per l'harvesting.
/// Supporta diversi tipi di portali (CKAN, Socrata, DCAT).
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Portal {
    /// Nome del portale (human-readable)
    pub name: String,
    /// URL base del portale
    pub url: String,
    /// Tipo di portale ("ckan", "socrata", "dcat")
    #[serde(rename = "type")]
    pub portal_type: String,
    /// Se il portale è abilitato per l'harvesting
    #[serde(default = "default_enabled")]
    pub enabled: bool,
    /// Descrizione opzionale del portale
    pub description: Option<String>,
}

/// Default value for Portal.enabled field
fn default_enabled() -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_portal_default_enabled() {
        let json = r#"{
            "name": "Test Portal",
            "url": "https://example.com",
            "type": "ckan"
        }"#;

        let portal: Portal = serde_json::from_str(json).unwrap();
        assert!(portal.enabled);
    }

    #[test]
    fn test_new_dataset_creation() {
        let dataset = NewDataset {
            original_id: "test-123".to_string(),
            source_portal: "https://example.com".to_string(),
            url: "https://example.com/dataset/test".to_string(),
            title: "Test Dataset".to_string(),
            description: Some("A test dataset".to_string()),
            embedding: None,
            metadata: serde_json::json!({"key": "value"}),
        };

        assert_eq!(dataset.original_id, "test-123");
        assert!(dataset.embedding.is_none());
    }
}
